apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- deployment.yml
- podinfo-deployment.yaml
- podinfo-registry.yaml
- podinfo-policy.yaml
- flux-system-automation.yaml
